# Generated by Django 2.1.7 on 2019-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190307_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default='2019-03-07 11:04:29'),
        ),
    ]
